### ISSUE TITLE
"403 Client Error: Forbidden for url"

### ISSUE THREAD

**Issue by onedayblack** [streamlink-plugins/streamlink-plugins#5] opened 2023-04-20 11:27 UTC
Hello, 
I'm using 5.2.1 version.

```
C:\Users\username>streamlink -o C:\Users\desktop018\comPluChe\test1.mp4 https://chaturbate.com/**username**/ best
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/**username**/
error: Unable to open URL: https://chaturbate.com/api/chatvideocontext/**username** (403 Client Error: Forbidden for url: https://chaturbate.com/api/chatvideocontext/**username**)
```

I getting this error. "403 Client Error: Forbidden for URL" - What would be the reason?

**Comment by odnar-dev** [comment] 2023-04-22 11:27
I never had this problem, do you get this error for all streamers or only for some?
please try to update streamlink to [version 5.4.0](https://github.com/streamlink/streamlink/releases/tag/5.4.0)

**Comment by emresaracoglu** [comment] 2023-04-22 14:59
Hello, unfortunately, it applies to all publishers and I'm using version 5.4

**Comment by onedayblack** [comment] 2023-04-22 15:02
All publishers get the same error. I tried it on both windows and Debian OS. The result has not changed, also im using v5.4

**Comment by justcallmejc** [comment] 2023-08-30 14:30
I am now having the same problem, it's being caused by cloudflare based on what I have researched so far because it's also affecting CTBREC. using a differnt public IP on a totally different computer doesn't resolve the problem. on a computer where streamlink gets a 403, web browser's work fine, but receive a captcha prompt from cloudflare fwiw.

something that might prove very useful for streamlink that is beyond my skillset would be the implementation of cloudscraper or something similar.
https://github.com/VeNoMouS/cloudscraper

**Comment by odnar-dev** [comment] 2023-09-05 21:58
i was already testing a version that use cloudscraper  in [this branch](https://github.com/community-plugins/streamlink-plugins/tree/cloudscraper)
try downloading this version and give me a feedback if it work for you
https://raw.githubusercontent.com/community-plugins/streamlink-plugins/cloudscraper/plugins/chaturbate.py

**Comment by justcallmejc** [comment] 2023-09-09 14:24
> i was already testing a version that use cloudscraper in [this branch](https://github.com/community-plugins/streamlink-plugins/tree/cloudscraper) try downloading this version and give me a feedback if it work for you https://raw.githubusercontent.com/community-plugins/streamlink-plugins/cloudscraper/plugins/chaturbate.py

the linked chaturbate.py file works as expected!

**Comment by odnar-dev** [comment] 2024-02-14 20:16
i will be closing this for now, if you still having this problem please open a new issue

**Comment by onedayblack** [comment] 2024-02-15 05:32
> i will be closing this for now, if you still having this problem please open a new issue

Please, Thank you for your help

**Closed as completed** 2024-02-18 12:13 UTC
